export  const   VALIDAR_FORMULARIO  =   'VALIDAR_FORMULARIO';
export  const   VALIDAR_FORMULARIO_EXITO  =   'VALIDAR_FORMULARIO_EXITO';
export  const   VALIDAR_FORMULARIO_ERROR  =   'VALIDAR_FORMULARIO_ERROR';

export  const   INICIAR_LOGIN  =   'INICIAR_LOGIN';
export  const   INICIAR_LOGIN_EXITO  =   'INICIAR_LOGIN_EXITO';
export  const   INICIAR_LOGIN_ERROR  =   'INICIAR_LOGIN_ERROR';

export  const   AGREGAR_PRESTAMO  =   'AGREGAR_PRESTAMO';
export  const   AGREGAR_PRESTAMO_EXITO  =   'AGREGAR_PRESTAMO_EXITO';
export  const   AGREGAR_PRESTAMO_ERROR  =   'AGREGAR_PRESTAMO_ERROR';

export  const   MAS_DEMANDADOS  =   'MAS_DEMANDADOS';
export  const   MAS_DEMANDADOS_EXITO  =   'MAS_DEMANDADOS_EXITO';
export  const   MAS_DEMANDADOS_ERROR  =   'MAS_DEMANDADOS_ERROR';

export const    USO_BIBLIOTECA  =   'USO_BIBLIOTECA';
export const    USO_BIBLIOTECA_EXITO    =   'USO_BIBLIOTECA_EXITO';
export const    USO_BIBLIOTECA_ERROR    =   'USO_BIBLIOTECA_ERROR';

export  const   UTIL_DOCUMENTOS  =   'UTIL_DOCUMENTOS';
export  const   UTIL_DOCUMENTOS_EXITO  =   'UTIL_DOCUMENTOS_EXITO';
export  const   UTIL_DOCUMENTOS_ERROR  =   'UTIL_DOCUMENTOS_ERROR';

export  const   NUM_DOCUMENTOS  =   'NUM_DOCUMENTOS';
export  const   NUM_DOCUMENTOS_EXITO  =   'NUM_DOCUMENTOS_EXITO';
export  const   NUM_DOCUMENTOS_ERROR  =   'NUM_DOCUMENTOS_ERROR';

export  const   SIN_FOLIADO  =   'SIN_FOLIADO';
export  const   SIN_FOLIADO_EXITO  =   'SIN_FOLIADO_EXITO';
export  const   SIN_FOLIADO_ERROR  =   'SIN_FOLIADO_ERROR';

export  const   SANCION_USUARIO  =   'SANCION_USUARIO';
export  const   SANCION_USUARIO_EXITO  =   'SANCION_USUARIO_EXITO';
export  const   SANCION_USUARIO_ERROR  =   'SANCION_USUARIO_ERROR';

export  const   INICIAR_SANCION_EXITO  =   'INICIAR_SANCION_EXITO';

export  const   DEVOLUCION  =   'DEVOLUCION';
export  const   DEVOLUCION_EXITO  =   'DEVOLUCION_EXITO';
export  const   DEVOLUCION_ERROR  =   'DEVOLUCION_ERROR';