export  const   VALIDAR_FORMULARIO  =   'VALIDAR_FORMULARIO';
export  const   VALIDAR_FORMULARIO_EXITO  =   'VALIDAR_FORMULARIO_EXITO';
export  const   VALIDAR_FORMULARIO_ERROR  =   'VALIDAR_FORMULARIO_ERROR';

export  const   AGREGAR_PRESTAMO  =   'AGREGAR_PRESTAMO';
export  const   AGREGAR_PRESTAMO_EXITO  =   'AGREGAR_PRESTAMO_EXITO';
export  const   AGREGAR_PRESTAMO_ERROR  =   'AGREGAR_PRESTAMO_ERROR';